add_newline = false
prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "memory_usage",
    "cmd_duration",
    "line_break",
    "jobs",
    "time",
    "character",
]

[line_break]
disabled = true
